"use client";

import { createContext, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { usePathname } from "next/navigation";

export type AppLanguage = "en" | "ru" | "tk";
type LanguageContextValue = { language: AppLanguage; setLanguage: (language: AppLanguage) => void; text: (english: string, russian: string, turkmen?: string) => string };

const LanguageContext = createContext<LanguageContextValue | null>(null);

const viewTranslations: Record<string, string> = {
  "Loading your reading space…": "Загружаем ваше пространство для чтения…", "Make every book yours.": "Сделайте каждую книгу своей.", "Sign in to choose a plan, keep reading progress, and build your bookshelf.": "Войдите, чтобы выбрать план, сохранять прогресс и собирать свою библиотеку.", "Create free account": "Создать бесплатный аккаунт",
  "Every story, translation, and audio track is open.": "Все истории, переводы и аудиодорожки открыты.", "Enjoy your first book part, then upgrade whenever you’re ready.": "Читайте первую часть книги бесплатно и подключите Pro, когда будете готовы.",
  "YOUR READING SPACE": "ВАШЕ ПРОСТРАНСТВО ДЛЯ ЧТЕНИЯ", "Account settings →": "Настройки аккаунта →", "saved books": "сохранённых книг", "saved words": "сохранённых слов", "Active until": "Активна до", "Upgrade anytime": "Можно улучшить в любое время",
  "MEMBERSHIP": "ПОДПИСКА", "Choose how you read": "Выберите формат чтения", "Frontend preview · API ready": "Предпросмотр фронтенда · готово к API", "FREE": "БЕСПЛАТНО", "Start every story": "Начните любую историю", "Explore the library and try the reading experience before upgrading.": "Изучайте библиотеку и попробуйте чтение перед оформлением подписки.", "Read the first part of every book": "Читайте первую часть каждой книги", "Audio until that part ends": "Аудио до конца этой части", "Word translations": "Перевод слов", "No saved books": "Без сохранения книг", "Current plan": "Текущий план", "Switch to Free": "Перейти на бесплатный", "Promo is active": "Промокод активен",
  "FULL EXPERIENCE": "ПОЛНЫЙ ДОСТУП", "Keep every story going": "Продолжайте каждую историю", "Read without chapter limits and keep a personal shelf.": "Читайте без ограничений и собирайте личную библиотеку.", "Read every book from start to finish": "Читайте каждую книгу от начала до конца", "Full-book audio": "Полное аудио книги", "Translations and saved progress": "Переводы и сохранённый прогресс", "Save books to your profile": "Сохраняйте книги в профиле", "Pro is active": "Pro активен", "Preview Pro": "Попробовать Pro",
  "HAVE A PROMO CODE?": "ЕСТЬ ПРОМОКОД?", "Open a little more time to read.": "Откройте больше времени для чтения.", "Redeem a code for temporary Pro access—from a few days to a full year.": "Активируйте временный доступ Pro — от нескольких дней до целого года.", "ACTIVE": "АКТИВЕН", "Promo code": "Промокод", "Redeem": "Активировать", "Frontend test codes": "Тестовые коды фронтенда",
  "BILLING": "ОПЛАТА", "Payment methods": "Способы оплаты", "Store only your payment provider’s card ID and display details here. Full card numbers and security codes never belong in the frontend.": "Здесь хранятся только ID карты платёжного провайдера и данные для отображения. Полные номера карт и коды безопасности не сохраняются во фронтенде.", "No payment methods added yet.": "Способы оплаты ещё не добавлены.", "Add payment reference": "Добавить платёжные данные", "Payment card ID": "ID платёжной карты", "Cardholder name": "Имя владельца карты", "Name on card": "Имя на карте", "Brand": "Банк", "CVC": "CVC", "CVC is checked for this form only and is never saved.": "CVC проверяется только в этой форме и никогда не сохраняется.", "Add card reference": "Добавить карту", "Remove": "Удалить",
  "SAVED FOR LATER": "СОХРАНЕНО НА ПОТОМ", "Your bookshelf": "Ваша книжная полка", "Browse library →": "Открыть библиотеку →", "Bookshelf is a Pro feature": "Книжная полка доступна в Pro", "Upgrade to save books here and return to them anytime.": "Подключите Pro, чтобы сохранять книги и возвращаться к ним в любое время.", "See Pro plan": "Посмотреть Pro", "Your bookshelf is empty. Save a book to find it here.": "Ваша полка пуста. Сохраните книгу, и она появится здесь.",
  "ACCOUNT SETTINGS": "НАСТРОЙКИ АККАУНТА", "Your profile": "Ваш профиль", "Display name": "Имя", "Email": "Эл. почта", "Save changes": "Сохранить", "Saving…": "Сохранение…",
  "Profile saved.": "Профиль сохранён.", "Your display name needs at least 2 characters.": "Имя должно содержать не менее 2 символов.", "We couldn’t save that change. Please try again.": "Не удалось сохранить изменения. Попробуйте снова.", "Payment method removed.": "Способ оплаты удалён.", "Payment method saved in this browser.": "Способ оплаты сохранён в этом браузере.", "That payment card ID is already saved.": "Этот ID карты уже сохранён.", "Add the card ID, cardholder name, and a valid CVC.": "Укажите ID карты, имя владельца и корректный CVC.",
  "Library": "Библиотека", "Ready when you are": "Можно начинать", "Your place is saved": "Ваше место сохранено", "Begin reading": "Начать чтение", "Continue reading": "Продолжить чтение", "See plans →": "Посмотреть планы →", "Full text, translation and audio included": "Полный текст, перевод и аудио включены", "First text part and matching audio included": "Первая часть текста и соответствующее аудио включены", "Reading level": "Уровень чтения", "Listen & read": "Слушайте и читайте", "At your own pace": "В своём темпе", "In this book": "В этой книге", "passages": "отрывков", "Short, focused lessons": "Короткие уроки", "First published": "Первая публикация", "A lasting favorite": "Книга вне времени", "THE READING EXPERIENCE": "ПРОЦЕСС ЧТЕНИЯ", "A story made": "История стала", "approachable.": "понятнее.", "Read with confidence": "Читайте уверенно", "Original text and a clear translation sit side by side.": "Оригинал и понятный перевод расположены рядом.", "Listen as you go": "Слушайте во время чтения", "Hear the story aloud and follow every sentence.": "Слушайте историю и следите за каждым предложением.", "Make it your own": "Сделайте чтение своим", "Save words and return to the parts that moved you.": "Сохраняйте слова и возвращайтесь к важным местам.",
  "A guided reading experience by": "Чтение с поддержкой от", "A remarkable story to read slowly, listen to carefully, and make your own.": "Замечательная история, которую хочется читать не спеша, внимательно слушать и проживать по-своему.", "Move through the text sentence by sentence, with helpful tools there when you want them — and quietly out of the way when you do not.": "Читайте предложение за предложением: полезные инструменты рядом, когда нужны, и не мешают в остальное время.", "This book is unavailable.": "Эта книга недоступна.", "Loading book…": "Загрузка книги…", "Saving books is a Pro feature. Upgrade from your profile.": "Сохранение книг доступно в Pro. Подключите его в профиле.", "Saved to your bookshelf.": "Книга сохранена на вашей полке.", "Sign in to save books.": "Войдите, чтобы сохранять книги.", "We could not save this book. Please try again.": "Не удалось сохранить книгу. Попробуйте снова.",
  "FREE PREVIEW COMPLETE": "БЕСПЛАТНЫЙ ФРАГМЕНТ ЗАВЕРШЁН", "Keep the story going.": "Продолжите историю.", "You reached the end of the free chapter. Upgrade to Pro for every text part, full audio, translations, and saved books.": "Вы дошли до конца бесплатной главы. Pro откроет весь текст, полное аудио, переводы и сохранение книг.", "Not now": "Не сейчас", "Free preview": "Бесплатный фрагмент", "Now reading": "Сейчас читается", "Preparing your reading room": "Готовим пространство для чтения", "Your book": "Ваша книга", "Opening the first passages and getting the audio ready.": "Открываем первые отрывки и готовим аудио.", "English reader": "Чтение на английском", "Translate words to": "Переводить слова на", "Russian": "Русский", "Turkish": "Турецкий", "Original text": "Оригинальный текст", "translation": "перевод", "Translation unavailable": "Перевод недоступен", "Loading previous passages…": "Загружаем предыдущие отрывки…", "Loading more…": "Загружаем ещё…", "Hide translation": "Скрыть перевод", "Show translation": "Показать перевод", "Switching to": "Переход к", "Save": "Сохранить", "Saved": "Сохранено", "Audio could not be loaded. Please try again.": "Не удалось загрузить аудио. Попробуйте снова.", "Unable to load the book text.": "Не удалось загрузить текст книги.", "Unable to load book details.": "Не удалось загрузить данные книги.", "Unable to load the book.": "Не удалось загрузить книгу.", "Unable to load that part of the book.": "Не удалось загрузить эту часть книги.", "Unable to translate this word.": "Не удалось перевести это слово.", "This book does not have readable text files yet.": "Для этой книги пока нет доступного текста."
};

const turkmenTranslations: Record<string, string> = {
  "Language": "Dil", "English": "Iňlisçe", "Russian": "Rusça", "Turkmen": "Türkmençe",
  "Library": "Kitaphana", "My books": "Kitaplarym", "Log in": "Giriş", "Sign in": "Giriş", "Sign up": "Hasaba dur", "Sign out": "Çyk", "Open profile": "Profili aç", "Free": "Mugt",
  "Loading your reading space…": "Okamak üçin ýeriňiz ýüklenýär…", "Preparing your reading space…": "Okamak üçin ýeriňiz taýýarlanýar…", "Just a moment while everything falls into place.": "Hemme zat taýýarlanýança biraz garaşyň.", "Loading books": "Kitaplar ýüklenýär", "Loading book…": "Kitap ýüklenýär…",
  "Make every book yours.": "Her kitaby özüňizki ediň.", "Sign in to choose a plan, keep reading progress, and build your bookshelf.": "Meýilnama saýlamak, ösüşiňizi saklamak we kitap tekjäňizi döretmek üçin giriň.", "Create free account": "Mugt hasap aç",
  "Every story, translation, and audio track is open.": "Ähli hekaýalar, terjimeler we ses ýazgylary açyk.", "Enjoy your first book part, then upgrade whenever you’re ready.": "Kitabyň ilkinji bölegini okaň, taýýar bolanyňyzda Pro-a geçiň.",
  "YOUR READING SPACE": "SIZIŇ OKAÝYŞ ÝERIŇIZ", "Account settings →": "Hasap sazlamalary →", "saved books": "saklanan kitap", "saved words": "saklanan söz", "Active until": "Şu wagta çenli işjeň", "Upgrade anytime": "Islän wagtyňyz täzeläň",
  "MEMBERSHIP": "AGZALYK", "Choose how you read": "Nähili okajakdygyňyzy saýlaň", "Synced with your account": "Hasabyňyz bilen sinhronlandy", "FREE": "MUGT", "Start every story": "Her hekaýany başlaň", "Explore the library and try the reading experience before upgrading.": "Kitaphanany öwreniň we Pro-a geçmezden öň okamak tejribesini synap görüň.", "Read the first part of every book": "Her kitabyň ilkinji bölegini okaň", "Audio until that part ends": "Şol bölek gutarýança ses", "Word translations": "Söz terjimeleri", "No saved books": "Kitap saklap bolmaýar", "Current plan": "Häzirki meýilnama", "Switch to Free": "Mugt meýilnama geç", "Promo is active": "Promo işjeň",
  "FULL EXPERIENCE": "DOLY MÜMKINÇILIK", "Keep every story going": "Her hekaýany dowam etdiriň", "Read without chapter limits and keep a personal shelf.": "Bölüm çäklendirmesiz okaň we şahsy tekjäňizi dörediň.", "Read every book from start to finish": "Her kitaby başyndan ahyryna çenli okaň", "Full-book audio": "Kitabyň doly sesi", "Translations and saved progress": "Terjimeler we saklanan ösüş", "Save books to your profile": "Kitaplary profiliňize saklaň", "Pro is active": "Pro işjeň", "Preview Pro": "Pro-ny syna",
  "HAVE A PROMO CODE?": "PROMO KODUŇYZ BARMY?", "Open a little more time to read.": "Okamak üçin has köp wagt açyň.", "Redeem a code for temporary Pro access—from a few days to a full year.": "Birnäçe günden bir ýyla çenli wagtlaýyn Pro üçin kody ulanyň.", "ACTIVE": "IŞJEŇ", "Promo code": "Promo kod", "Redeem": "Ulan", "Frontend test codes": "Frontend synag kodlary",
  "BILLING": "TÖLEG", "Payment methods": "Töleg usullary", "Store only your payment provider’s card ID and display details here. Full card numbers and security codes never belong in the frontend.": "Bu ýerde diňe töleg üpjün edijiniň kart ID-si we görkezilýän maglumatlar saklanýar. Doly kart belgisi we howpsuzlyk kody frontend-de saklanmaýar.", "No payment methods added yet.": "Töleg usuly entek goşulmady.", "Add payment reference": "Töleg maglumatyny goş", "Payment card ID": "Töleg kartynyň ID-si", "Cardholder name": "Kart eýesiniň ady", "Name on card": "Kartdaky at", "Brand": "Bank", "CVC": "CVC", "CVC is checked for this form only and is never saved.": "CVC diňe şu forma üçin barlanýar we hiç wagt saklanmaýar.", "Add card reference": "Karty goş", "Remove": "Aýyr",
  "SAVED FOR LATER": "SOŇRA ÜÇIN SAKLANAN", "Your bookshelf": "Kitap tekjäňiz", "Browse library →": "Kitaphanany aç →", "Bookshelf is a Pro feature": "Kitap tekjesi Pro mümkinçiligidir", "Upgrade to save books here and return to them anytime.": "Kitaplary saklamak we olara gaýdyp gelmek üçin Pro-a geçiň.", "See Pro plan": "Pro meýilnamasyny gör", "Your bookshelf is empty. Save a book to find it here.": "Kitap tekjäňiz boş. Bu ýerde görmek üçin kitap saklaň.",
  "ACCOUNT SETTINGS": "HASAP SAZLAMALARY", "Your profile": "Profiliňiz", "Display name": "Görkezilýän at", "Email": "E-poçta", "Save changes": "Üýtgeşmeleri sakla", "Saving…": "Saklanýar…", "Profile saved.": "Profil saklandy.", "Your display name needs at least 2 characters.": "Görkezilýän at azyndan 2 harp bolmaly.", "We couldn’t save that change. Please try again.": "Üýtgeşmäni saklap bolmady. Gaýtadan synanyşyň.", "Payment method removed.": "Töleg usuly aýryldy.", "Payment method saved in this browser.": "Töleg usuly şu brauzerde saklandy.", "That payment card ID is already saved.": "Bu töleg kartynyň ID-si eýýäm saklanan.", "Add the card ID, cardholder name, and a valid CVC.": "Kart ID-sini, kart eýesiniň adyny we dogry CVC-ni giriziň.",
  "Ready when you are": "Taýýar bolanyňyzda", "Your place is saved": "Ýeriňiz saklandy", "Begin reading": "Okap başla", "Continue reading": "Okamagy dowam et", "See plans →": "Meýilnamalary gör →", "Full text, translation and audio included": "Doly tekst, terjime we ses bar", "First text part and matching audio included": "Tekstiň ilkinji bölegi we degişli ses bar", "Reading level": "Okamak derejesi", "Listen & read": "Diňle we oka", "At your own pace": "Öz tizligiňizde", "In this book": "Bu kitapda", "passages": "bölek", "Short, focused lessons": "Gysga we anyk sapaklar", "First published": "Ilkinji neşir", "A lasting favorite": "Hemişelik söýgüli eser",
  "THE READING EXPERIENCE": "OKAMAK TEJRIBESI", "A story made": "Hekaýa indi", "approachable.": "has düşnükli.", "Read with confidence": "Ynam bilen oka", "Original text and a clear translation sit side by side.": "Asyl tekst bilen düşnükli terjime gapdal-galdal ýerleşýär.", "Listen as you go": "Okaýarkaňyz diňläň", "Hear the story aloud and follow every sentence.": "Hekaýany diňläň we her sözlemi yzarlaň.", "Make it your own": "Özüňize laýyk ediň", "Save words and return to the parts that moved you.": "Sözleri saklaň we täsir eden ýerleriňize gaýdyň.",
  "This book is unavailable.": "Bu kitap elýeterli däl.", "Saving books is a Pro feature. Upgrade from your profile.": "Kitap saklamak Pro mümkinçiligidir. Profiliňizden Pro-a geçiň.", "Saved to your bookshelf.": "Kitap tekjäňize saklandy.", "Sign in to save books.": "Kitap saklamak üçin giriň.", "We could not save this book. Please try again.": "Kitaby saklap bolmady. Gaýtadan synanyşyň.",
  "FREE PREVIEW COMPLETE": "MUGT BÖLEK TAMAMLANDY", "Keep the story going.": "Hekaýany dowam etdiriň.", "You reached the end of the free chapter. Upgrade to Pro for every text part, full audio, translations, and saved books.": "Mugt bölümiň soňuna ýetdiňiz. Ähli tekst, doly ses, terjimeler we kitap saklamak üçin Pro-a geçiň.", "Not now": "Häzir däl", "Free preview": "Mugt bölek", "Now reading": "Häzir okalýar", "Preparing your reading room": "Okamak otagyňyz taýýarlanýar", "Your book": "Kitabyňyz", "Opening the first passages and getting the audio ready.": "Ilkinji bölekler açylýar we ses taýýarlanýar.", "English reader": "Iňlisçe okaýyş", "Translate words to": "Sözleri şu dile terjime et", "Turkish": "Türkçe", "Original text": "Asyl tekst", "translation": "terjime", "Translation unavailable": "Terjime elýeterli däl", "Loading previous passages…": "Öňki bölekler ýüklenýär…", "Loading more…": "Ýene ýüklenýär…", "Hide translation": "Terjimäni gizle", "Show translation": "Terjimäni görkez", "Switching to": "Geçilýär", "Save": "Sakla", "Saved": "Saklandy",
  "Audio could not be loaded. Please try again.": "Sesi ýükläp bolmady. Gaýtadan synanyşyň.", "Unable to load the book text.": "Kitabyň tekstini ýükläp bolmady.", "Unable to load book details.": "Kitap maglumatlaryny ýükläp bolmady.", "Unable to load the book.": "Kitaby ýükläp bolmady.", "Unable to load that part of the book.": "Kitabyň şol bölegini ýükläp bolmady.", "Unable to translate this word.": "Bu sözi terjime edip bolmady.", "This book does not have readable text files yet.": "Bu kitap üçin okalýan tekst faýllary entek ýok.",
  "All genres": "Ähli žanrlar", "All levels": "Ähli derejeler", "Book pages": "Kitap sahypalary", "Books for every mood": "Her bir keýp üçin kitap", "Choose a story at your reading level.": "Derejäňize laýyk hekaýa saýlaň.", "Classic edition": "Klassyky neşir", "Classic stories, modern tools": "Klassyky hekaýalar, döwrebap gurallar", "Cover of": "Daşky suraty", "ENGLISH LIBRARY": "IŇLISÇE KITAPHANA", "English books,": "Iňlisçe kitaplar,", "English classic": "Iňlis klassikasy", "Every book pairs the original English text with an easy translation, natural audio and progress tracking.": "Her kitapda iňlisçe asyl tekst, ýeňil terjime, tebigy ses we ösüş yzarlamasy bar.", "Explore books": "Kitaplary öwren", "FIND YOUR NEXT STORY": "INDIKI HEKAÝAŇYZY TAPYŇ", "Find a story you’ll love.": "Göwnüňizden turjak hekaýany tapyň.", "Genre": "Žanr", "Learn at your own pace": "Öz tizligiňizde öwreniň", "Level": "Dereje", "Listen": "Diňle", "Listen and repeat": "Diňle we gaýtala", "No books found.": "Kitap tapylmady.", "Pick a book": "Kitap saýla", "READ • LISTEN • UNDERSTAND": "OKA • DIŇLE • DÜŞÜN", "Read original stories line by line, with translation and audio always beside you.": "Asyl hekaýalary setirme-setir, terjime we ses bilen okaň.", "Search books": "Kitap gözle", "Search by title or author": "Ady ýa-da awtory boýunça gözle", "See a clear translation whenever you need it.": "Gerek wagty düşnükli terjimäni görüň.", "See all books": "Ähli kitaplary gör", "THE LIBRARY": "KITAPHANA", "Train your ear with natural audio.": "Tebigy ses bilen diňleme ukybyňyzy ösdürüň.", "Unable to connect to your library": "Kitaphanaňyza birigip bolmady", "Your library is unavailable right now.": "Kitaphanaňyz häzir elýeterli däl.", "made friendly.": "has düşnükli.",
  "CREATE YOUR ACCOUNT": "HASAP AÇYŇ", "WELCOME BACK": "HOŞ GELDIŇIZ", "Already have an account?": "Hasabyňyz barmy?", "At least 8 characters": "Azyndan 8 nyşan", "Create account": "Hasap aç", "Create an account to save your books and learning progress.": "Kitaplaryňyzy we ösüşiňizi saklamak üçin hasap açyň.", "Create one": "Hasap aç", "Connecting…": "Birikdirilýär…", "I agree to the terms of use": "Ulanyş şertleri bilen razylaşýaryn", "New to Kitapchy?": "Kitapchy-da täzemi?", "One page at a time.": "Her gezek bir sahypa.", "Password": "Açar söz", "Sign in to pick up where you left off.": "Galan ýeriňizden dowam etmek üçin giriň.", "Start your reading habit.": "Okamak endigiňizi başlaň.", "Use a password with at least 8 characters.": "Azyndan 8 nyşanly açar söz ulanyň.", "We couldn’t sign you in. Check your details and try again.": "Giriş başartmady. Maglumatlaryňyzy barlap, gaýtadan synanyşyň.", "Welcome back": "Hoş geldiňiz", "Welcome back.": "Hoş geldiňiz.", "Welcome back. Opening your reading space…": "Hoş geldiňiz. Okamak ýeriňiz açylýar…", "Your account is ready. Opening your reading space…": "Hasabyňyz taýýar. Okamak ýeriňiz açylýar…",
  "Choose a plan": "Meýilnama saýla", "Choose plan": "Meýilnamany saýla", "Confirm mock payment": "Synag tölegini tassykla", "Confirming…": "Tassyklanýar…", "Creating…": "Döredilýär…", "Ends": "Gutarýar", "Enter your code": "Koduňyzy giriziň", "PAYMENT READY": "TÖLEGE TAÝÝAR", "PRO PLANS": "PRO MEÝILNAMALARY", "Prices from the server": "Serwerden alnan bahalar", "Reference": "Salgylanma", "Select your reading time": "Okamak wagtyňyzy saýlaň", "Start with the first passage": "Ilkinji bölekden başla", "Subscription active": "Abuna işjeň", "1 month of Pro": "1 aý Pro", "3 months of Pro": "3 aý Pro", "6 months of Pro": "6 aý Pro", "1 year of Pro": "1 ýyl Pro",
  "Next": "Indiki", "Previous": "Öňki", "Translating…": "Terjime edilýär…", "Close translation": "Terjimäni ýap", "Play": "Aýtdyr", "Pause": "Sakla",
  "Could not create the purchase. Please try again.": "Tölegi döredip bolmady. Gaýtadan synanyşyň.", "Payment could not be confirmed. Mock confirmation may be disabled on this server.": "Tölegi tassyklap bolmady. Synag tassyklamasy bu serwerde öçürilen bolup biler.", "The subscription was not returned by the server.": "Serwer abuna maglumatyny gaýtarmady.", "Sign-in succeeded, but no usable session was returned. Please contact support.": "Giriş üstünlikli boldy, emma sessiýa döredilmedi. Goldaw gullugyna ýüz tutuň.",
};

function translateViewText(value: string, language: AppLanguage) {
  const fixed = language === "tk"
    ? turkmenTranslations[value]
    : viewTranslations[value] || ({ "Pro · full book": "Pro · полная книга", "by": "автор:" } as Record<string, string>)[value];
  if (fixed) return fixed;
  const passage = value.match(/^Passage (\d+)$/); if (passage) return language === "tk" ? `Bölek ${passage[1]}` : `Отрывок ${passage[1]}`;
  const saved = value.match(/^(\d+) saved$/); if (saved) return language === "tk" ? `${saved[1]} saklandy` : `${saved[1]} сохранено`;
  const savedWords = value.match(/^(\d+) saved words$/); if (savedWords) return language === "tk" ? `${savedWords[1]} söz saklandy` : `${savedWords[1]} сохранённых слов`;
  return undefined;
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const pathname = usePathname();
  const [language, setLanguageState] = useState<AppLanguage>("en");
  const originalText = useRef(new WeakMap<Text, string>());
  useEffect(() => {
    const stored = localStorage.getItem("kitapchy_language");
    const next = stored === "ru" || stored === "tk" ? stored : "en";
    setLanguageState(next); document.documentElement.lang = next;
  }, []);
  const setLanguage = (next: AppLanguage) => { setLanguageState(next); localStorage.setItem("kitapchy_language", next); document.documentElement.lang = next; };
  const value = useMemo(() => ({ language, setLanguage, text: (english: string, russian: string, turkmen?: string) => language === "ru" ? russian : language === "tk" ? turkmen || turkmenTranslations[english] || english : english }), [language]);
  useEffect(() => {
    const translateNode = (root: Node) => {
      const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
      let node: Node | null = root.nodeType === Node.TEXT_NODE ? root : walker.nextNode();
      while (node) {
        const textNode = node as Text; const stored = originalText.current.get(textNode); const hasTranslation = translateViewText(textNode.data.trim(), language); const currentEnglish = hasTranslation ? textNode.data : null; const raw = currentEnglish && currentEnglish !== stored ? currentEnglish : stored || textNode.data; const normalized = raw.trim(); const translated = translateViewText(normalized, language);
        if (translated) { originalText.current.set(textNode, raw); const leading = raw.match(/^\s*/)?.[0] || ""; const trailing = raw.match(/\s*$/)?.[0] || ""; const next = language === "en" ? raw : `${leading}${translated}${trailing}`; if (textNode.data !== next) textNode.data = next; }
        node = walker.nextNode();
      }
    };
    translateNode(document.body);
    const observer = new MutationObserver((mutations) => mutations.forEach((mutation) => { mutation.addedNodes.forEach(translateNode); if (mutation.type === "characterData") translateNode(mutation.target); }));
    observer.observe(document.body, { childList: true, characterData: true, subtree: true });
    return () => observer.disconnect();
  }, [language]);
  const standaloneView = pathname.startsWith("/auth") || pathname.endsWith("/read");
  return <LanguageContext.Provider value={value}>{standaloneView && <LanguageDropdown standalone />}{children}</LanguageContext.Provider>;
}

const languageOptions: Array<{ code: AppLanguage; short: string; name: string }> = [
  { code: "en", short: "EN", name: "English" },
  { code: "ru", short: "RU", name: "Русский" },
  { code: "tk", short: "TM", name: "Türkmençe" },
];

export function LanguageDropdown({ standalone = false, className = "" }: { standalone?: boolean; className?: string }) {
  const { language, setLanguage, text } = useLanguage();
  const [open, setOpen] = useState(false);
  const rootRef = useRef<HTMLDivElement>(null);
  const selected = languageOptions.find((option) => option.code === language) || languageOptions[0];
  useEffect(() => {
    const close = (event: PointerEvent) => { if (!rootRef.current?.contains(event.target as Node)) setOpen(false); };
    document.addEventListener("pointerdown", close);
    return () => document.removeEventListener("pointerdown", close);
  }, []);
  return <div ref={rootRef} className={`language-dropdown ${standalone ? "standalone-language" : ""} ${className}`}>
    <button className="language-trigger" type="button" aria-label={text("Language", "Язык", "Dil")} aria-haspopup="listbox" aria-expanded={open} onClick={() => setOpen((value) => !value)}>
      <span className="language-code">{selected.short}</span><span className="language-current">{selected.name}</span><span className="language-chevron" aria-hidden="true">⌄</span>
    </button>
    {open && <div className="language-menu" role="listbox" aria-label={text("Language", "Язык", "Dil")}>
      {languageOptions.map((option) => <button type="button" role="option" aria-selected={language === option.code} className={language === option.code ? "active" : ""} key={option.code} onClick={() => { setLanguage(option.code); setOpen(false); }}><span>{option.short}</span><strong>{option.name}</strong>{language === option.code && <i aria-hidden="true">✓</i>}</button>)}
    </div>}
  </div>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}
